greeting: "default greeting2"

userconfig:
    greeting: "userconfig default greeting"
    greeting2: "userconfig default greeting2"
    greeting3: 1001
---

spring:
  profiles: dev

greeting: "dev greeting2"
userconfig:
    greeting: "dev default greeting"
    greeting2: "dev default greeting2"
    greeting3: 1001
---

spring:
  profiles: stg

greeting: "stg greeting2"
userconfig:
    greeting: "stg default greeting"
    greeting2: "stg default greeting2"
    greeting3: 1001
---

spring:
  profiles: prd

greeting: "prd greeting2"
userconfig:
    greeting: "prd default greeting"
    greeting2: "prd default greeting2"
    greeting3: 1001