greeting: "default greeting2"

---

spring:
  profiles: dev

greeting: "dev greeting2"

---

spring:
  profiles: stg

greeting: "stg greeting2"

---

spring:
  profiles: prd

greeting: "prd greeting2"
